name: Build Docker Image

on:
  push:
    tags:
      - 'v*.*.*'     # Для production теги (например, v1.0.0)
      - 'dev-*'      # Для dev-сборок по тегам, начинающимся на dev-

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/remnawave-telegram-sub-mini-app
          tags: |
            type=raw,value=dev-latest,enable=${{ startsWith(github.ref_name, 'dev-') }}
            type=raw,value=${{ github.ref_name }},enable=${{ startsWith(github.ref_name, 'dev-') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref_name, 'v') }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref_name, 'v') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref_name, 'v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref_name, 'v') }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  send-notification:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set commit message
        id: commit-message
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            # For tag events
            TAG_MSG=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
            if [ -z "$TAG_MSG" ]; then
              TAG_MSG="Release ${{ github.ref_name }}"
            fi
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            # For dev branch events
            TAG_MSG="Development build for dev"
          else
            # For workflow_dispatch or other events
            TAG_MSG="${{ github.event.head_commit.message || format('Manual build from {0}', github.ref_name) }}"
          fi
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Build finished.
            🚀 Project: remnawave-telegram-mini-app
            🛠️ Branch: ${{ github.ref_name }}
            📝 Message: ${{ steps.commit-message.outputs.message }}
            🔗 Image: ghcr.io/${{ github.repository_owner }}/remnawave-telegram-sub-mini-app:${{ github.ref_name == 'dev' && 'dev-latest' || github.ref_name }}
